const colors = {
  light: {
    text: "#1C1C1E",
    tint: "#FF6B35",
    background: "#F7F8FA",
    foreground: "#1C1C1E",
    card: "#FFFFFF",
    cardForeground: "#1C1C1E",
    primary: "#FF6B35",
    primaryForeground: "#FFFFFF",
    primaryLight: "#FF6B3515",
    primaryDark: "#E8521A",
    secondary: "#6B7280",
    secondaryForeground: "#FFFFFF",
    accent: "#FF6B35",
    accentForeground: "#FFFFFF",
    muted: "#F3F4F6",
    mutedForeground: "#8E8E93",
    border: "#F0F0F2",
    input: "#F7F8FA",
    surface: "#F3F4F6",
    surfaceElevated: "#FFFFFF",
    cyan: "#3B82F6",
    orange: "#FF6B35",
    green: "#22C55E",
    purple: "#8B5CF6",
    yellow: "#F59E0B",
    red: "#EF4444",
    success: "#22C55E",
    warning: "#F59E0B",
    error: "#EF4444",
    info: "#3B82F6",
    destructive: "#EF4444",
    destructiveForeground: "#FFFFFF",
    dark: "#1C1C1E",
    darkCard: "#2C2C2E",
  },
  dark: {
    text: "#F4F4F5",
    tint: "#FF6B35",
    background: "#070B14",
    foreground: "#FFFFFF",
    card: "#121826",
    cardForeground: "#FFFFFF",
    primary: "#FF6B35",
    primaryForeground: "#FFFFFF",
    primaryLight: "#FF6B3525",
    primaryDark: "#E8521A",
    secondary: "#94A3B8",
    secondaryForeground: "#070B14",
    accent: "#FF6B35",
    accentForeground: "#FFFFFF",
    muted: "#1A2233",
    mutedForeground: "#94A3B8",
    border: "#1E293B",
    input: "#121826",
    surface: "#0D1219",
    surfaceElevated: "#161D2E",
    cyan: "#38BDF8",
    orange: "#FF6B35",
    green: "#4ADE80",
    purple: "#A78BFA",
    yellow: "#FBBF24",
    red: "#F87171",
    success: "#4ADE80",
    warning: "#FBBF24",
    error: "#F87171",
    info: "#38BDF8",
    destructive: "#F87171",
    destructiveForeground: "#FFFFFF",
    dark: "#070B14",
    darkCard: "#121826",
    ringTrack: "#1E293B",
    gradientStart: "#121826",
    gradientEnd: "#1A1035",
  },
  radius: 16,
  radiusSmall: 10,
  radiusLarge: 24,
  radiusFull: 9999,
  spacing: {
    xs: 4,
    sm: 8,
    md: 16,
    lg: 20,
    xl: 24,
    xxl: 32,
  },
  shadow: {
    soft: {
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.06,
      shadowRadius: 8,
      elevation: 2,
    },
    medium: {
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.10,
      shadowRadius: 16,
      elevation: 5,
    },
    strong: {
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 8 },
      shadowOpacity: 0.14,
      shadowRadius: 24,
      elevation: 10,
    },
  },
  typography: {
    h1: { fontSize: 28, lineHeight: 34, fontFamily: "Inter_700Bold", letterSpacing: -0.5 },
    h2: { fontSize: 22, lineHeight: 28, fontFamily: "Inter_700Bold", letterSpacing: -0.3 },
    h3: { fontSize: 17, lineHeight: 22, fontFamily: "Inter_600SemiBold" },
    body: { fontSize: 15, lineHeight: 22, fontFamily: "Inter_400Regular" },
    bodyMedium: { fontSize: 15, lineHeight: 22, fontFamily: "Inter_500Medium" },
    caption: { fontSize: 13, lineHeight: 18, fontFamily: "Inter_400Regular" },
    label: { fontSize: 11, lineHeight: 14, fontFamily: "Inter_600SemiBold", letterSpacing: 0.8, textTransform: "uppercase" as const },
    tiny: { fontSize: 11, lineHeight: 14, fontFamily: "Inter_400Regular" },
  },
};

export type ColorTokens = typeof colors.light;
export type ThemeTokens = ColorTokens & {
  radius: typeof colors.radius;
  radiusSmall: typeof colors.radiusSmall;
  radiusLarge: typeof colors.radiusLarge;
  radiusFull: typeof colors.radiusFull;
  spacing: typeof colors.spacing;
  shadow: typeof colors.shadow;
  typography: typeof colors.typography;
};

export default colors;
